/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Isak.G (https://sketchfab.com/isakglindronn)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/saradomin-godsword-osrs-2e07b636a0804ed8aa29c8af2bbb3188
title: Saradomin Godsword Osrs
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.blinn1SG} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.blinn2SG} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials.blinn3SG} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials.lambert3SG} />
      </group>
    </group>
  )
}

useGLTF.preload('scene.gltf')
